apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAupl8ufSkNI4lJ9oeUrVQXWdxWd7iTgBNBsXlIh0yjv928kbkQKXjy4zHxE/H4dOXsGLG7iok6pw0WPfiUz9gVLkdLMo+Vy+LMB80thJaQDa4SJzE/J5gb3eYzNh7Yrf0PX12nKiL6SRu4zF5RRg2ZyxJQjFZzFo8XS4ZuZ1sOJ05xht8ldWAw+vba4Cwb2qhkGnm2i+kpV76ZfgzahmgXM6NJBzo21Qcvw9sQRdlSp34Vw95OAtWjGhj1wJdGMhqhCWASxLTWMgD8r3Xx4Mo+1x0Kp1QSqp4X8/fLLAoqQ04yhQJbOVVLOfJiHPtvMVWfF0xilBpIUpUQ3a3imQO1C7NoVozu2GpN2mI9vfBKwzwIs3gblkC6f/mhWHWOGi9FifAh+jmmh3o1cUaRHMgPJPQebk0NaWuD3E9fxvd5GlvEKC//XLW/n7+G+10NrskEOpJSGvf73NS1Q0MWQCHY+/oCWo3UyaPXx/PAuF9Exkh7XvgkqJFOZDtZmV3jA/HDHOsuhSiPK0pULGESkWS4Fs7aiz7LFJVEm+bw8/8EyVCEhf8Q+0BY/GEIP9R6MjlVaYlw5FcsFot4ZiNfYUfWgm4AlV0lLqmEySYn4189dN6NrdrId3Q0SDjrJuFZDtUHKZ12aCqCI2OwT/rfj+WvkI347976zIQrKqo7JhjxrHyPK6TA8GsuAxQXHinb+veoXsKDA5C5Pg==
    MONGO_INITDB_ROOT_USERNAME: AgC9C6xGpX/AtKgqAyDo7Rk18AXYdR966WQRAMWmKUMzmqYB4tAO5iYi4lQY5ysPTAePfb0XuPSs8pcEjbXCUWDMqdVOt3VeTid7+4XCr8AdVTfCRcO1yqzxMX5ZmncOF4DGCqYO6cDBOpZp040XdWZb+ObF2LyB66srfmYdiObWpsQ8cA5HYb69X6xjc4zuEOMeGWayH27wPNYyUa1Eg/VR6aN1mPEYIwS2ciF+5lA/W14MJ3pFWiZeKQwsM0HZrgAF7zXZ6iI5tV3wCZTPWZkGYg1RTFcW8vGOqYwdbF8ZMpxL5vzLhObefXQruZUGaYH/8br+mZ+71rCt7+GIvpnv2HAsCV2V9EP/A6/mbNWpdrTEbOOtRbGHd3weaPiF20v23VqiWcvmSwF0yEqaXm/xFIcnOUhsCsTRbCOYHM4YwvBIGt+6KbBLS/LQiwk/bd8GB8ZpXRE2PCaMRE1sX1HyI6KSdJM8Q4YzSKd7pAHKjS3n+eNcdqebAhP5WR8DxJev6bM2wVy7Xylpt9xpuf/1dHmcBNundFTemJI3UgWN3QJlUZc5O8E1NMErZtGFtSrcnTzO2OpFudtfDShU7Fg/hFBS+EGECm2pbgYe+p0bWI6GiWTj3fkGkIAA5WDF1NOmJ2z/4qbYdB0ejBubfMJDhnaxaPJecmEdIo6CQxjL6z3xmI5wHCF5gP+WUV2oNppFXRQP
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: blog-app

